permalink:      /:year-:month-:day/:title.html
safe:           true
server_port:    4000
url:            http://localhost:4000
server:         true
auto:           true

source:         ./src
destination:    .jekyll
